models.py: hotfix
Fixes the following traceback:

Traceback (most recent call last):
  File "/usr/bin/rcl-import-results", line 5, in <module>
    pkg_resources.run_script('perfevents-result-collector==1.1', 'rcl-import-results')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/perfevents_result_collector-1.1-py2.7.egg/EGG-INFO/scripts/rcl-import-results", line 273, in <module>
    kernelsXkernel_id=kernel_id, virtXvirt_id=virt_id)
  File "/usr/lib/python2.7/site-packages/perfevents_result_collector-1.1-py2.7.egg/perfresultcollector/models.py", line 80, in getID_or_create
    self.insert_one(**stripped_kwargs)
  File "/usr/lib/python2.7/site-packages/perfevents_result_collector-1.1-py2.7.egg/perfresultcollector/models.py", line 174, in insert_one
    self.insert(table, **kwargs)
  File "/usr/lib/python2.7/site-packages/perfevents_result_collector-1.1-py2.7.egg/perfresultcollector/models.py", line 195, in insert
    kwargs_values[str(key) + str(index)] = value[index]
IndexError: list index out of range

Thanks to Martin Pavlasek.